services:
  # ------------------------ DB ------------------------
  db:
    image: postgres:16-alpine
    container_name: secureapp_db_prod
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./backend/db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./backend/certs:/etc/nginx/certs:ro
    networks:
      - secure_net

  # --------------------- Backend ----------------------
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: secureapp_backend_prod
    restart: unless-stopped
    depends_on:
      - db
    environment:
      NODE_ENV: production
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: ${JWT_EXPIRATION:-15m}
      REFRESH_EXPIRATION: ${REFRESH_EXPIRATION:-7d}
      FRONTEND_URL: ${FRONTEND_URL:-http://localhost:8080}
    volumes:
      - ./backend/certs:/app/certs:ro
    ports:
      - "4000:4000"
    networks:
      - secure_net

  # -------------------- Frontend ----------------------
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: secureapp_frontend_prod
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "8080:80"
    networks:
      - secure_net
    volumes:
    - ./backend/certs:/etc/nginx/certs:ro

  # --------------------- Adminer ----------------------
  adminer:
    image: adminer:latest
    container_name: secureapp_adminer_prod
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "8081:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=db
    networks:
      - secure_net

# --------------------- Volumes/Network ----------------
volumes:
  db_data:

networks:
  secure_net: